### ISSUE TITLE
Grit has encoding problems

### ISSUE THREAD

**Issue by Dahie** [Dahie/caramelize#6]
Some migrations fail with a grit error pointing to incompatible character encodings. This issues has been reported with grit before and could be addressed by switching to a different git adapter.

```
.rvm/gems/ruby-2.1.5@caramelize/gems/gitlab-grit-2.7.3/lib/grit/index.rb:176:in `%': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/gitlab-grit-2.7.3/lib/grit/index.rb:176:in `block in write_tree'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/gitlab-grit-2.7.3/lib/grit/index.rb:171:in `each'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/gitlab-grit-2.7.3/lib/grit/index.rb:171:in `write_tree'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/gitlab-grit-2.7.3/lib/grit/index.rb:123:in `commit'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/gollum-grit_adapter-0.1.3/lib/grit_adapter/git_layer_grit.rb:241:in `commit'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/ext.rb:10:in `commit'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/gollum-lib-4.0.2/lib/gollum-lib/wiki.rb:453:in `update_page'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/gollum_output.rb:26:in `commit_revision'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/gollum_output.rb:38:in `block in commit_history'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/gollum_output.rb:35:in `each'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/gollum_output.rb:35:in `each_with_index'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/gollum_output.rb:35:in `commit_history'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/content_transferer.rb:93:in `commit_history'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/content_transferer.rb:39:in `execute'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/cli.rb:69:in `commence_transfer'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/cli.rb:56:in `transfer_content'
  from /Users/danielsenff/.rvm/gems/ruby-2.1.5@caramelize/gems/caramelize-0.3.0/lib/caramelize/cli/run_command.rb:28:in `execute'
```

**Comment by Dahie** [comment]
Fixed with Gollum 5 and the switch to rugged as git adapter instead of grit
